# -*- coding: utf-8 -*-

'''
A wrapper of PyMuPDF Page as page engine.
'''

import fitz
import logging
from .RawPage import RawPage
from ..image.ImagesExtractor import ImagesExtractor
from ..shape.Paths import Paths
from ..common.constants import FACTOR_A_HALF
from ..common.Element import Element
from ..common.share import (RectType, debug_plot)
from ..common.share import rgb_value
from ..common.algorithm import get_area


class RawPageFitz(RawPage):
    '''A wrapper of ``fitz.Page`` to extract source contents.'''

    def extract_raw_dict(self, **settings):
        raw_dict = {}
        if not self.page_engine: return raw_dict

        # actual page size
        # `self.page_engine` is the `fitz.Page`.
        *_, w, h = self.page_engine.rect # always reflecting page rotation
        raw_dict.update({ 'width' : w, 'height': h })
        self.width, self.height = w, h

        # pre-processing layout elements. e.g. text, images and shapes
        text_blocks = self._preprocess_text(**settings)
        raw_dict['blocks'] = text_blocks

        image_blocks = self._preprocess_images(**settings)
        raw_dict['blocks'].extend(image_blocks)

        # Hyperlinks are used both as semantic shapes and to de-duplicate
        # decorative line graphics generated by some PDFs.
        hyperlinks = self._preprocess_hyperlinks()

        shapes, images =  self._preprocess_shapes(**settings)
        images, style_shapes = self._filter_text_style_strip_images(images, text_blocks, hyperlinks)
        raw_dict['shapes'] = shapes
        raw_dict['shapes'].extend(style_shapes)
        raw_dict['blocks'].extend(images)

        raw_dict['shapes'].extend(hyperlinks)
       
        # Element is a base class processing coordinates, so set rotation matrix globally
        Element.set_rotation_matrix(self.page_engine.rotation_matrix)

        return raw_dict
    

    def _preprocess_text(self, **settings):
        '''Extract page text and identify hidden text. 
        
        NOTE: All the coordinates are relative to un-rotated page.

            https://pymupdf.readthedocs.io/en/latest/page.html#modifying-pages
            https://pymupdf.readthedocs.io/en/latest/functions.html#Page.get_texttrace
            https://pymupdf.readthedocs.io/en/latest/textpage.html
        '''
        ocr = settings['ocr']
        if ocr==1: raise SystemExit("OCR feature is planned but not implemented yet.")

        # all text blocks no matter hidden or not
        sort = settings.get('sort')
        raw = self.page_engine.get_text(
                'rawdict',
                flags=0
                    | fitz.TEXT_MEDIABOX_CLIP
                    | fitz.TEXT_CID_FOR_UNKNOWN_UNICODE
                    ,
                sort=sort,
                )
        text_blocks = raw.get('blocks', [])

        # potential UnicodeDecodeError issue when trying to filter hidden text:
        # https://github.com/dothinking/pdf2docx/issues/144
        # https://github.com/dothinking/pdf2docx/issues/155
        try:
            spans = self.page_engine.get_texttrace()
        except SystemError:
            logging.warning('Ignore hidden text checking due to UnicodeDecodeError in upstream library.')
            spans = []
        
        if not spans: return text_blocks

        # ignore hidden text if ocr=0, while extract only hidden text if ocr=2
        if ocr==2:
            f = lambda span: span['type']!=3  # find displayed text and ignore it
        else:
            f = lambda span: span['type']==3  # find hidden text and ignore it
        filtered_spans = list(filter(f, spans))
        
        def span_area(bbox):
            x0, y0, x1, y1 = bbox
            return (x1-x0) * (y1-y0)

        # filter blocks by checking span intersection: mark the entire block if 
        # any span is matched
        blocks = []
        for block in text_blocks:
            intersected = False
            for line in block['lines']:
                for span in line['spans']:
                    for filter_span in filtered_spans:
                        intersected_area = get_area(span['bbox'], filter_span['bbox'])
                        if intersected_area / span_area(span['bbox']) >= FACTOR_A_HALF \
                            and span['font']==filter_span['font']:
                            intersected = True
                            break
                    if intersected: break # skip further span check if found
                if intersected: break     # skip further line check

            # keep block if no any intersection with filtered span
            if not intersected: blocks.append(block)

        return blocks


    def _preprocess_images(self, **settings):
        '''Extract image blocks. Image block extracted by ``page.get_text('rawdict')`` doesn't 
        contain alpha channel data, so it has to get page images by ``page.get_images()`` and 
        then recover them. Note that ``Page.get_images()`` contains each image only once, i.e., 
        ignore duplicated occurrences.
        '''
        # ignore image if ocr-ed pdf: get ocr-ed text only
        if settings['ocr']==2: return []
        
        return ImagesExtractor(self.page_engine).extract_images(settings['clip_image_res_ratio'])


    def _preprocess_shapes(self, **settings):
        '''Identify iso-oriented paths and convert vector graphic paths to pixmap.'''
        paths = self._init_paths(**settings)
        return paths.to_shapes_and_images(
            settings['min_svg_gap_dx'], 
            settings['min_svg_gap_dy'], 
            settings['min_svg_w'], 
            settings['min_svg_h'], 
            settings['clip_image_res_ratio'])
    

    @debug_plot('Source Paths')
    def _init_paths(self, **settings):
        '''Initialize Paths based on drawings extracted with PyMuPDF.'''
        raw_paths = self.page_engine.get_cdrawings()
        return Paths(parent=self).restore(raw_paths)
    

    def _preprocess_hyperlinks(self):
        """Get source hyperlink dicts.

        Returns:
            list: A list of source hyperlink dict.
        """
        hyperlinks = []
        drawings = self.page_engine.get_cdrawings()
        for link in self.page_engine.get_links():
            if link['kind']!=2: continue # consider internet address only
            bbox = tuple(link['from'])
            color = self._estimate_hyperlink_color(bbox, drawings)
            hyperlinks.append({
                'type': RectType.HYPERLINK.value,
                'bbox': bbox,
                'uri' : link['uri'],
                'color': color
            })

        return hyperlinks


    def _filter_text_style_strip_images(self, images, text_blocks, _hyperlinks):
        """Convert decorative underline-like strips to text style shapes.

        Vector extraction may convert decorative underlines into inline image
        blocks (especially when mixed with non-iso paths). This method detects
        thin strips in text-baseline positions and converts them to synthetic
        stroke shapes so normal text style parsing can apply.
        """
        if not images:
            return images, []

        text_bboxes = self._collect_text_bboxes(text_blocks)
        kept_images = []
        style_shapes = []
        for image in images:
            bbox_raw = image.get('bbox')
            if not bbox_raw:
                kept_images.append(image)
                continue

            bbox = fitz.Rect(bbox_raw)
            if not self._is_thin_strip(bbox):
                kept_images.append(image)
                continue

            baseline_hit = any(self._is_baseline_strip_for_text(bbox, tb) for tb in text_bboxes)
            if not baseline_hit:
                kept_images.append(image)
                continue

            # Preserve semantics by converting strip image to a stroke shape.
            style_shapes.append(self._image_strip_to_stroke_shape(image, bbox))

        return kept_images, style_shapes


    @staticmethod
    def _collect_text_bboxes(text_blocks):
        bboxes = []
        for block in text_blocks or []:
            for line in block.get('lines', []):
                for span in line.get('spans', []):
                    bbox = fitz.Rect(span.get('bbox', (0, 0, 0, 0)))
                    if bbox.is_empty:
                        continue
                    bboxes.append(bbox)
        return bboxes


    @staticmethod
    def _is_thin_strip(bbox):
        w, h = bbox.width, bbox.height
        short, long_ = (min(w, h), max(w, h))
        ratio = long_ / (short or 1.0)
        return short <= 3.5 and long_ >= 8.0 and ratio >= 4.0


    @staticmethod
    def _is_baseline_strip_for_text(strip_bbox, text_bbox):
        inter = strip_bbox & text_bbox
        overlap_w = inter.width
        if overlap_w <= 0:
            return False

        # Significant horizontal overlap with nearby text.
        overlap_ratio = overlap_w / (strip_bbox.width or 1.0)
        if overlap_ratio < 0.60:
            return False

        text_h = text_bbox.height or 1.0
        # Underline zone: near the bottom border of text bbox.
        d = abs(text_bbox.y1 - strip_bbox.y0)
        near_baseline = d <= max(1.5, 0.35 * text_h)
        in_lower_band = strip_bbox.y0 >= text_bbox.y0 + 0.55 * text_h
        short_enough = strip_bbox.width <= text_bbox.width + 8.0
        return near_baseline and in_lower_band and short_enough


    @staticmethod
    def _image_strip_to_stroke_shape(image, bbox):
        color = 0
        image_bytes = image.get('image', b'')
        if isinstance(image_bytes, str):
            try:
                import base64
                image_bytes = base64.b64decode(image_bytes.encode())
            except Exception:
                image_bytes = b''

        if image_bytes:
            try:
                pix = fitz.Pixmap(image_bytes)
                samples = pix.samples
                n = pix.n
                if samples and n >= 3:
                    # Use first non-white pixel as representative color.
                    for i in range(0, len(samples), n):
                        r, g, b = samples[i], samples[i + 1], samples[i + 2]
                        if not (r > 245 and g > 245 and b > 245):
                            color = (r << 16) + (g << 8) + b
                            break
                pix = None
            except Exception:
                pass

        y = (bbox.y0 + bbox.y1) / 2.0
        return {
            'type': -1,
            'bbox': tuple(bbox),
            'color': color,
            'start': (bbox.x0, y),
            'end': (bbox.x1, y),
            'width': bbox.height
        }


    @staticmethod
    def _estimate_hyperlink_color(bbox, drawings):
        """Estimate hyperlink text color from vector drawings around link bbox."""
        rect = fitz.Rect(bbox)
        if rect.is_empty:
            return 0

        white = rgb_value((1, 1, 1))
        scores = {}
        max_area = rect.get_area() * 4.0

        for drawing in drawings:
            fill = drawing.get('fill')
            if fill is None:
                continue
            d_rect = fitz.Rect(drawing.get('rect'))
            if not d_rect.intersects(rect):
                continue
            if d_rect.get_area() > max_area:
                continue

            inter = (d_rect & rect).get_area()
            if inter <= 0:
                continue

            c = rgb_value(fill)
            if c == white:
                continue
            scores[c] = scores.get(c, 0.0) + inter

        if not scores:
            return 0
        return max(scores.items(), key=lambda item: item[1])[0]
